name: Release Tag
on:
  push:
    branches:
      - main # main branch로 push될 때 아래 action이 실행.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃헙 코드 내려받기
      - uses: actions/checkout@v2

      # 태그 생성
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5 # 가져다 쓸 auto tagging 프로그램
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # secrets.GITHUB_TOKEN 는 자동생성됨

      # 릴리즈 생성
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1 # 가져다 쓸 create release 프로그램
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # secrets.GITHUB_TOKEN 는 자동생성됨
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
